### ISSUE TITLE
pathod project link redirects to mitmproxy.org

### ISSUE THREAD

**Issue by SamuAlfageme** [mitmproxy/www#2]
Just noticed the pathod link to the docs: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/36717954-54ab8732-1ba0-11e8-97b1-625fe3708a85.png"/>
</p>

... is broken. Link is http://docs.mitmproxy.org/en/stable/pathod/intro.html resolves to mitmproxy.org. 

I was unable to find the pathod section on the new docs: https://mitmproxy.org/docs/latest/

**Comment by mhils** [comment]
Thanks, good catch. The old docs are [here](https://mitmproxy.readthedocs.io/en/v2.0.2/pathod/intro.html), I think we decided to move this into a README in the repo. In any case we should fix the link.

**Comment by Kriechi** [comment]
Thanks - this should be fixed now, and the link points to the old docs for pathod 2.0.2.
