### ISSUE TITLE
Firefox: CORS Request Blocked

### ISSUE THREAD

**Issue by N3X15** [mitmproxy/www#27]
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s3-us-west-2.amazonaws.com/snapshots.mitmproxy.org?delimiter=/&prefix=. (Reason: CORS request did not succeed).

TypeError: NetworkError when attempting to fetch resource.
```
​Error:
![image](https://user-images.githubusercontent.com/110073/80908993-4ca69980-8cd9-11ea-85a0-1c7254bd9b19.png)

Downloads page stuck in download loop:
![image](https://user-images.githubusercontent.com/110073/80908998-60ea9680-8cd9-11ea-835b-584795a3c5a3.png)

Firefox 75.0 on Windows 10 Pro x64.

**Comment by Kriechi** [comment]
Interesting - it works for me with Firefox 75.0 on macOS, and Chrome 81.0.4044.129 on macOS.

@N3X15 do you have any special privacy or security extensions installed that might be more strict than the default?

A quick web search also yields results indicated problems with the server certificate which could cause this error message...

I checked visiting the mitmproxy downloads page through an active mitmproxy session - and it also works, so I can't be cert or key pinning.
