### ISSUE TITLE
pathod link on main page is no longer valid

### ISSUE THREAD

**Issue by meitinger** [mitmproxy/www#41]
Currently links to https://mitmproxy.readthedocs.io/en/v2.0.2/pathod/intro.html, which yields a 404 message.

Maybe link to https://docs.mitmproxy.org/archive/v2/index.html#document-pathod/intro instead or remove alltogether?

**Comment by mhils** [comment]
Good catch. I think we can remove pathod (dead), tamper (dead), bdfproxy (not FOSS anymore), and mastermind (dead) from the section. There are a few newer projects we can add instead, for example https://github.com/alufers/mitmproxy2swagger or https://github.com/xepor/xepor. :)
