### ISSUE TITLE
List of available downloads not showing

### ISSUE THREAD

**Issue by nafanz** [mitmproxy/www#47]
When you go to the Downloads section, there is no list of files (see attachment)

Perhaps this is a consequence of Certificate Expired #46
![Снимок экрана от 2023-02-03 10-03-58](https://user-images.githubusercontent.com/36957143/216517297-2e7ebe0e-cbe6-47a0-9140-6ade393a7d19.png)

**Comment by mhils** [comment]
This works just fine for me. Can anyone else reproduce?

**Comment by decathorpe** [comment]
It works for me as well.

**Comment by nafanz** [comment]
Could it be because of the country? I'm from Russia.

**Comment by Prinzhorn** [comment]
Can you access the bucket directly? https://s3-us-west-2.amazonaws.com/snapshots.mitmproxy.org?delimiter=/&prefix=

If not, can you access this S3 region at all? https://s3-us-west-2.amazonaws.com/ should redirect to the S3 product page

**Comment by nafanz** [comment]
Both links are not available, checked through the browser and curl
```
curl -i https://s3-us-west-2.amazonaws.com/
curl: (35) OpenSSL SSL_connect: Соединение разорвано другой стороной in connection to s3-us-west-2.amazonaws.com:443 
```

**Comment by mhils** [comment]
Ok, then that's a problem with your local connection and nothing we can do anything about - sorry about that!

**Comment by nafanz** [comment]
Found a workaround, works without VPN.
It may be useful to someone, so I'll leave it as a note.
```
wget https://snapshots.mitmproxy.org/9.0.1/mitmproxy-9.0.1-linux.tar.gz
```
