### ISSUE TITLE
Downloads sorting

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/www#50]
Just noticed that the sorting order is not what you'd expect:

![image](https://github.com/mitmproxy/www/assets/679144/9af9fa51-3e45-4afd-9742-77d3bd57ad8e)

Or is this on purpose? I swear it was different in the past.

**Comment by mhils** [comment]
This was updated to prefer 10. over 9... seems like we need to revisit. :)

**Comment by Prinzhorn** [comment]
Maybe we can drop sth. like https://www.npmjs.com/package/natural-compare-lite in instead of figuring it out ourselves? Assuming it does work for this use case.
