### ISSUE TITLE
"Download" button in main page gives a 404 error

### ISSUE THREAD

**Issue by q2dg** [mitmproxy/www#6]
In my case (I use Linux), link wants to go to https://github.com/mitmproxy/mitmproxy/releases/download/v3.0.4/mitmproxy-3.0.4-linux.tar.gz  but there's nothing there. I think there is a missing "v" here in file name before "3.0.4". This silly error gives a very bad first impression to web visitor

**Comment by mhils** [comment]
Thank you very much for reporting this. It looks like we messed up filename generation for Linux - the Windows link and OSX instructions were unaffected. I manually renamed them this time, I'll leave this open so that we fix it properly.

**Comment by Kriechi** [comment]
With the recent changes to our release process and scripts, this should be fixed now.
